// Code generated by protoc-gen-go. DO NOT EDIT.
// source: twos.proto

package twos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Two struct {
	Value                float32  `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Two) Reset()         { *m = Two{} }
func (m *Two) String() string { return proto.CompactTextString(m) }
func (*Two) ProtoMessage()    {}
func (*Two) Descriptor() ([]byte, []int) {
	return fileDescriptor_twos_372428eb10879d8c, []int{0}
}
func (m *Two) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Two.Unmarshal(m, b)
}
func (m *Two) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Two.Marshal(b, m, deterministic)
}
func (dst *Two) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Two.Merge(dst, src)
}
func (m *Two) XXX_Size() int {
	return xxx_messageInfo_Two.Size(m)
}
func (m *Two) XXX_DiscardUnknown() {
	xxx_messageInfo_Two.DiscardUnknown(m)
}

var xxx_messageInfo_Two proto.InternalMessageInfo

func (m *Two) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type GetTwoRequest struct {
	Value                *Two     `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTwoRequest) Reset()         { *m = GetTwoRequest{} }
func (m *GetTwoRequest) String() string { return proto.CompactTextString(m) }
func (*GetTwoRequest) ProtoMessage()    {}
func (*GetTwoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_twos_372428eb10879d8c, []int{1}
}
func (m *GetTwoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTwoRequest.Unmarshal(m, b)
}
func (m *GetTwoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTwoRequest.Marshal(b, m, deterministic)
}
func (dst *GetTwoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTwoRequest.Merge(dst, src)
}
func (m *GetTwoRequest) XXX_Size() int {
	return xxx_messageInfo_GetTwoRequest.Size(m)
}
func (m *GetTwoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTwoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTwoRequest proto.InternalMessageInfo

func (m *GetTwoRequest) GetValue() *Two {
	if m != nil {
		return m.Value
	}
	return nil
}

type GetTwoResponse struct {
	Value                *Two     `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTwoResponse) Reset()         { *m = GetTwoResponse{} }
func (m *GetTwoResponse) String() string { return proto.CompactTextString(m) }
func (*GetTwoResponse) ProtoMessage()    {}
func (*GetTwoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_twos_372428eb10879d8c, []int{2}
}
func (m *GetTwoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTwoResponse.Unmarshal(m, b)
}
func (m *GetTwoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTwoResponse.Marshal(b, m, deterministic)
}
func (dst *GetTwoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTwoResponse.Merge(dst, src)
}
func (m *GetTwoResponse) XXX_Size() int {
	return xxx_messageInfo_GetTwoResponse.Size(m)
}
func (m *GetTwoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTwoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTwoResponse proto.InternalMessageInfo

func (m *GetTwoResponse) GetValue() *Two {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Two)(nil), "Two")
	proto.RegisterType((*GetTwoRequest)(nil), "GetTwoRequest")
	proto.RegisterType((*GetTwoResponse)(nil), "GetTwoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TwosClient is the client API for Twos service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TwosClient interface {
	EchoTwo(ctx context.Context, in *GetTwoRequest, opts ...grpc.CallOption) (*GetTwoResponse, error)
}

type twosClient struct {
	cc *grpc.ClientConn
}

func NewTwosClient(cc *grpc.ClientConn) TwosClient {
	return &twosClient{cc}
}

func (c *twosClient) EchoTwo(ctx context.Context, in *GetTwoRequest, opts ...grpc.CallOption) (*GetTwoResponse, error) {
	out := new(GetTwoResponse)
	err := c.cc.Invoke(ctx, "/Twos/EchoTwo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TwosServer is the server API for Twos service.
type TwosServer interface {
	EchoTwo(context.Context, *GetTwoRequest) (*GetTwoResponse, error)
}

func RegisterTwosServer(s *grpc.Server, srv TwosServer) {
	s.RegisterService(&_Twos_serviceDesc, srv)
}

func _Twos_EchoTwo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTwoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwosServer).EchoTwo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Twos/EchoTwo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwosServer).EchoTwo(ctx, req.(*GetTwoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Twos_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Twos",
	HandlerType: (*TwosServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EchoTwo",
			Handler:    _Twos_EchoTwo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "twos.proto",
}

func init() { proto.RegisterFile("twos.proto", fileDescriptor_twos_372428eb10879d8c) }

var fileDescriptor_twos_372428eb10879d8c = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x29, 0xcf, 0x2f,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x92, 0xe6, 0x62, 0x0e, 0x29, 0xcf, 0x17, 0x12, 0xe1,
	0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0a, 0x82, 0x70, 0x94,
	0xb4, 0xb9, 0x78, 0xdd, 0x53, 0x4b, 0x42, 0xca, 0xf3, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b,
	0x84, 0xa4, 0x90, 0x95, 0x71, 0x1b, 0xb1, 0xe8, 0x81, 0xe4, 0xa0, 0x8a, 0x75, 0xb8, 0xf8, 0x60,
	0x8a, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0xf1, 0xa9, 0x36, 0x32, 0xe1, 0x62, 0x09, 0x29, 0xcf,
	0x2f, 0x16, 0xd2, 0xe1, 0x62, 0x77, 0x4d, 0xce, 0xc8, 0x07, 0xb9, 0x81, 0x4f, 0x0f, 0xc5, 0x32,
	0x29, 0x7e, 0x3d, 0x54, 0xf3, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0x8e, 0x36, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xce, 0xdd, 0x44, 0x95, 0xc2, 0x00, 0x00, 0x00,
}
