# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: threes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='threes.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0cthrees.proto\"\x16\n\x05Three\x12\r\n\x05value\x18\x01 \x01(\x02\"(\n\x0fGetThreeRequest\x12\x15\n\x05value\x18\x01 \x01(\x0b\x32\x06.Three\")\n\x10GetThreeResponse\x12\x15\n\x05value\x18\x01 \x01(\x0b\x32\x06.Three2<\n\x06Threes\x12\x32\n\tEchoThree\x12\x10.GetThreeRequest\x1a\x11.GetThreeResponse\"\x00\x62\x06proto3')
)




_THREE = _descriptor.Descriptor(
  name='Three',
  full_name='Three',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Three.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=38,
)


_GETTHREEREQUEST = _descriptor.Descriptor(
  name='GetThreeRequest',
  full_name='GetThreeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='GetThreeRequest.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=80,
)


_GETTHREERESPONSE = _descriptor.Descriptor(
  name='GetThreeResponse',
  full_name='GetThreeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='GetThreeResponse.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=123,
)

_GETTHREEREQUEST.fields_by_name['value'].message_type = _THREE
_GETTHREERESPONSE.fields_by_name['value'].message_type = _THREE
DESCRIPTOR.message_types_by_name['Three'] = _THREE
DESCRIPTOR.message_types_by_name['GetThreeRequest'] = _GETTHREEREQUEST
DESCRIPTOR.message_types_by_name['GetThreeResponse'] = _GETTHREERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Three = _reflection.GeneratedProtocolMessageType('Three', (_message.Message,), dict(
  DESCRIPTOR = _THREE,
  __module__ = 'threes_pb2'
  # @@protoc_insertion_point(class_scope:Three)
  ))
_sym_db.RegisterMessage(Three)

GetThreeRequest = _reflection.GeneratedProtocolMessageType('GetThreeRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETTHREEREQUEST,
  __module__ = 'threes_pb2'
  # @@protoc_insertion_point(class_scope:GetThreeRequest)
  ))
_sym_db.RegisterMessage(GetThreeRequest)

GetThreeResponse = _reflection.GeneratedProtocolMessageType('GetThreeResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETTHREERESPONSE,
  __module__ = 'threes_pb2'
  # @@protoc_insertion_point(class_scope:GetThreeResponse)
  ))
_sym_db.RegisterMessage(GetThreeResponse)



_THREES = _descriptor.ServiceDescriptor(
  name='Threes',
  full_name='Threes',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=125,
  serialized_end=185,
  methods=[
  _descriptor.MethodDescriptor(
    name='EchoThree',
    full_name='Threes.EchoThree',
    index=0,
    containing_service=None,
    input_type=_GETTHREEREQUEST,
    output_type=_GETTHREERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_THREES)

DESCRIPTOR.services_by_name['Threes'] = _THREES

# @@protoc_insertion_point(module_scope)
