# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from messages import twos_pb2 as twos__pb2


class TwosStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.EchoTwo = channel.unary_unary(
        '/Twos/EchoTwo',
        request_serializer=twos__pb2.GetTwoRequest.SerializeToString,
        response_deserializer=twos__pb2.GetTwoResponse.FromString,
        )


class TwosServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def EchoTwo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TwosServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'EchoTwo': grpc.unary_unary_rpc_method_handler(
          servicer.EchoTwo,
          request_deserializer=twos__pb2.GetTwoRequest.FromString,
          response_serializer=twos__pb2.GetTwoResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Twos', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
