# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: twos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='twos.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\ntwos.proto\"\x14\n\x03Two\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1e\n\rGetTwoRequest\x12\r\n\x05value\x18\x01 \x01(\x02\"%\n\x0eGetTwoResponse\x12\x13\n\x05value\x18\x01 \x01(\x0b\x32\x04.Two24\n\x04Twos\x12,\n\x07\x45\x63hoTwo\x12\x0e.GetTwoRequest\x1a\x0f.GetTwoResponse\"\x00\x62\x06proto3')
)




_TWO = _descriptor.Descriptor(
  name='Two',
  full_name='Two',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Two.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=34,
)


_GETTWOREQUEST = _descriptor.Descriptor(
  name='GetTwoRequest',
  full_name='GetTwoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='GetTwoRequest.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=66,
)


_GETTWORESPONSE = _descriptor.Descriptor(
  name='GetTwoResponse',
  full_name='GetTwoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='GetTwoResponse.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=105,
)

_GETTWORESPONSE.fields_by_name['value'].message_type = _TWO
DESCRIPTOR.message_types_by_name['Two'] = _TWO
DESCRIPTOR.message_types_by_name['GetTwoRequest'] = _GETTWOREQUEST
DESCRIPTOR.message_types_by_name['GetTwoResponse'] = _GETTWORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Two = _reflection.GeneratedProtocolMessageType('Two', (_message.Message,), dict(
  DESCRIPTOR = _TWO,
  __module__ = 'twos_pb2'
  # @@protoc_insertion_point(class_scope:Two)
  ))
_sym_db.RegisterMessage(Two)

GetTwoRequest = _reflection.GeneratedProtocolMessageType('GetTwoRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETTWOREQUEST,
  __module__ = 'twos_pb2'
  # @@protoc_insertion_point(class_scope:GetTwoRequest)
  ))
_sym_db.RegisterMessage(GetTwoRequest)

GetTwoResponse = _reflection.GeneratedProtocolMessageType('GetTwoResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETTWORESPONSE,
  __module__ = 'twos_pb2'
  # @@protoc_insertion_point(class_scope:GetTwoResponse)
  ))
_sym_db.RegisterMessage(GetTwoResponse)



_TWOS = _descriptor.ServiceDescriptor(
  name='Twos',
  full_name='Twos',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=107,
  serialized_end=159,
  methods=[
  _descriptor.MethodDescriptor(
    name='EchoTwo',
    full_name='Twos.EchoTwo',
    index=0,
    containing_service=None,
    input_type=_GETTWOREQUEST,
    output_type=_GETTWORESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TWOS)

DESCRIPTOR.services_by_name['Twos'] = _TWOS

# @@protoc_insertion_point(module_scope)
