# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ones.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ones.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nones.proto\"\x14\n\x03One\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1e\n\rGetOneRequest\x12\r\n\x05value\x18\x01 \x01(\x02\"%\n\x0eGetOneResponse\x12\x13\n\x05value\x18\x01 \x01(\x0b\x32\x04.One24\n\x04Ones\x12,\n\x07\x45\x63hoOne\x12\x0e.GetOneRequest\x1a\x0f.GetOneResponse\"\x00\x62\x06proto3')
)




_ONE = _descriptor.Descriptor(
  name='One',
  full_name='One',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='One.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=34,
)


_GETONEREQUEST = _descriptor.Descriptor(
  name='GetOneRequest',
  full_name='GetOneRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='GetOneRequest.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=66,
)


_GETONERESPONSE = _descriptor.Descriptor(
  name='GetOneResponse',
  full_name='GetOneResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='GetOneResponse.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=105,
)

_GETONERESPONSE.fields_by_name['value'].message_type = _ONE
DESCRIPTOR.message_types_by_name['One'] = _ONE
DESCRIPTOR.message_types_by_name['GetOneRequest'] = _GETONEREQUEST
DESCRIPTOR.message_types_by_name['GetOneResponse'] = _GETONERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

One = _reflection.GeneratedProtocolMessageType('One', (_message.Message,), dict(
  DESCRIPTOR = _ONE,
  __module__ = 'ones_pb2'
  # @@protoc_insertion_point(class_scope:One)
  ))
_sym_db.RegisterMessage(One)

GetOneRequest = _reflection.GeneratedProtocolMessageType('GetOneRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETONEREQUEST,
  __module__ = 'ones_pb2'
  # @@protoc_insertion_point(class_scope:GetOneRequest)
  ))
_sym_db.RegisterMessage(GetOneRequest)

GetOneResponse = _reflection.GeneratedProtocolMessageType('GetOneResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETONERESPONSE,
  __module__ = 'ones_pb2'
  # @@protoc_insertion_point(class_scope:GetOneResponse)
  ))
_sym_db.RegisterMessage(GetOneResponse)



_ONES = _descriptor.ServiceDescriptor(
  name='Ones',
  full_name='Ones',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=107,
  serialized_end=159,
  methods=[
  _descriptor.MethodDescriptor(
    name='EchoOne',
    full_name='Ones.EchoOne',
    index=0,
    containing_service=None,
    input_type=_GETONEREQUEST,
    output_type=_GETONERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ONES)

DESCRIPTOR.services_by_name['Ones'] = _ONES

# @@protoc_insertion_point(module_scope)
